using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DP_Observer_WeatherStation
{
    class WeatherData
    {
        private List<IWeatherDataObserver> _observersList = new List<IWeatherDataObserver>();
        private int _temp;
        private int _humidity;

        public void Register(IWeatherDataObserver observer)
        {
            _observersList.Add(observer);
        }

        public bool UnRegister(IWeatherDataObserver observer)
        {
            int indx = _observersList.FindIndex(
                                                delegate(IWeatherDataObserver obs)
                                                {
                                                    return obs == observer;
                                                });
            if(indx < 0)
            {
                return false;
            }
            else
            {
                _observersList.RemoveAt(indx);
                return true;
            }
                
        }

        // This function simulate getting the new data.
        // We call it from outside to test the design. in real life this could be 
        // generated by normal operation e.g. ResetCard.
        public void SetEvent(int temp, int humidity)
        {
            Console.WriteLine("SetEvent: temp = {0} , humidity = {1}", temp, humidity);

            _temp = temp;
            _humidity = humidity;
            NotifyObservers();
        }

        private void NotifyObservers()
        {
            foreach(IWeatherDataObserver obs in _observersList)
            {
                obs.Update(_temp, _humidity);
            }
        }
    }
}
